// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	CommentID    uuid.UUID      `json:"comment_id"`
	PostID       uuid.UUID      `json:"post_id"`
	CommentOnID  uuid.NullUUID  `json:"comment_on_id"`
	SubscriberID uuid.UUID      `json:"subscriber_id"`
	Content      string         `json:"content"`
	CreatedAt    time.Time      `json:"created_at"`
	CreatedBy    string         `json:"created_by"`
	UpdatedAt    time.Time      `json:"updated_at"`
	UpdatedBy    sql.NullString `json:"updated_by"`
}

type Post struct {
	PostID             uuid.UUID      `json:"post_id"`
	PostCategoryID     uuid.UUID      `json:"post_category_id"`
	Title              string         `json:"title"`
	Slug               string         `json:"slug"`
	Introduction       sql.NullString `json:"introduction"`
	Content            sql.NullString `json:"content"`
	MainImageAlt       sql.NullString `json:"main_image_alt"`
	MainImagePath      sql.NullString `json:"main_image_path"`
	ThumbnailImagePath sql.NullString `json:"thumbnail_image_path"`
	ThumbnailImageAlt  sql.NullString `json:"thumbnail_image_alt"`
	Author             string         `json:"author"`
	AuthorImagePath    string         `json:"author_image_path"`
	AuthorImageAlt     string         `json:"author_image_alt"`
	Published          bool           `json:"published"`
	PublishedAt        sql.NullTime   `json:"published_at"`
	PublishedBy        sql.NullString `json:"published_by"`
	CreatedAt          time.Time      `json:"created_at"`
	CreatedBy          string         `json:"created_by"`
	UpdatedAt          time.Time      `json:"updated_at"`
	UpdatedBy          sql.NullString `json:"updated_by"`
}

type PostCategory struct {
	PostCategoryID uuid.UUID      `json:"post_category_id"`
	Definition     string         `json:"definition"`
	CreatedAt      time.Time      `json:"created_at"`
	CreatedBy      string         `json:"created_by"`
	UpdatedAt      time.Time      `json:"updated_at"`
	UpdatedBy      sql.NullString `json:"updated_by"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Subscriber struct {
	SubscriberID uuid.UUID      `json:"subscriber_id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	CreatedAt    time.Time      `json:"created_at"`
	CreatedBy    string         `json:"created_by"`
	UpdatedAt    time.Time      `json:"updated_at"`
	UpdatedBy    sql.NullString `json:"updated_by"`
}

type User struct {
	Email             string         `json:"email"`
	HashedPassword    string         `json:"hashed_password"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	FirstName         string         `json:"first_name"`
	LastName          string         `json:"last_name"`
	ProfileImagePath  sql.NullString `json:"profile_image_path"`
	Salt              int32          `json:"salt"`
	LastLogin         time.Time      `json:"last_login"`
	CreatedAt         time.Time      `json:"created_at"`
	CreatedBy         string         `json:"created_by"`
	UpdatedAt         time.Time      `json:"updated_at"`
	UpdatedBy         sql.NullString `json:"updated_by"`
}
